id: I8A7C6114
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-17T04:53:06+00:00'
last_modified: '2022-06-10T05:02:28.511675+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1PD90002
  title: དཔལ་ཡུལ་རྫོང་གི་ལོ་རྒྱུས་དེབ་ཐེར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    74E7:
      image_group_id: I1PD90051
      title: Volume 1 of bai yu xian zhi
      total_pages: 616
      order: 1
      base_file: 74E7.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
